name: mapmybus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  latlong2: ^0.9.1
  flutter_map: ^8.2.1
  shared_preferences: ^2.5.3
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.2
  flutter_dotenv: ^5.2.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/routes.json
    - assets/data/stops.json
    - assets/data/trip_stops.json
    - assets/data/shapes.json